#!/usr/bin/env python3
"""Verify the z80pack ROM-profile RAM initialization representation."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from build_rom_ram_template import RAM_BASE, build, read_map


def get_word(data: bytes, offset: int) -> int:
    return data[offset] | data[offset + 1] << 8


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--z80pack-build", type=Path, required=True)
    parser.add_argument("--template", type=Path, required=True)
    args = parser.parse_args()
    expected, expected_manifest = build(args.z80pack_build.resolve())
    template = args.template.resolve()
    actual = (template / "ram-init.bin").read_bytes()
    manifest = json.loads((template / "ram-init.json").read_text(encoding="ascii"))
    if actual != expected:
        raise AssertionError("RAM initialization template differs from regenerated bytes")
    if manifest != expected_manifest:
        raise AssertionError("RAM initialization manifest differs from regenerated facts")
    if hashlib.sha256(actual).hexdigest() != manifest["sha256"]:
        raise AssertionError("RAM initialization hash does not describe the template")
    if manifest["immutable_source_bytes"] != 5370:
        raise AssertionError("current immutable-source measurement changed")
    if manifest["rom_used_before_initializer"] != 7782:
        raise AssertionError("current pre-initializer ROM budget changed")
    if manifest["rom_spare_before_initializer"] != 666:
        raise AssertionError("current pre-initializer ROM headroom changed")

    for row in read_map():
        if row["init_policy"] not in ("zero", "runtime"):
            continue
        start = int(row["ram_start"], 16) - RAM_BASE
        size = int(row["bytes"])
        if any(actual[start:start + size]):
            raise AssertionError(f"{row['entry']} is not zero before cold initialization")

    table = 0xD784 - RAM_BASE
    for drive in range(4):
        record = table + drive * 80
        expected_words = (
            0xD9ED,
            0xD784 + drive * 80 + 17,
            0xD784 + 448 + drive * 32,
            0xD784 + 320,
        )
        actual_words = tuple(
            get_word(actual, record + offset) for offset in (8, 10, 12, 14))
        if actual_words != expected_words:
            raise AssertionError(
                f"drive {drive} DPH pointers {actual_words!r}, expected {expected_words!r}")
    header = actual[0xD644 - RAM_BASE:0xD647 - RAM_BASE]
    if header != b"BM\x01":
        raise AssertionError(f"live descriptor header is {header!r}, expected b'BM\\x01'")
    print(f"ROM RAM template verified: {len(actual)} bytes, 16 relocated DPH pointers, "
          f"{manifest['rom_spare_before_initializer']} ROM bytes spare")


if __name__ == "__main__":
    main()
