#!/usr/bin/env python3
"""Generate the resident subsystem-version descriptor from the TSV matrix."""
from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MATRIX = ROOT / "metadata/subsystem-versions.tsv"
INCLUDE = ROOT / "src/bdos/versions.inc"


def rows() -> list[dict[str, str]]:
    with MATRIX.open(newline="", encoding="utf-8") as source:
        return list(csv.DictReader(source, delimiter="\t"))


LABELS = {"CCP": "C", "CPX": "X", "BDOS": "D", "RSX": "R", "BIOS": "I"}


def quoted(value: str) -> str:
    if not value.isascii() or "'" in value or "$" in value:
        raise ValueError(f"version metadata is not ZSM4-string-safe: {value!r}")
    return f"'{value}','$'"


def render() -> str:
    matrix = rows()
    system = next(row for row in matrix if row["component"] == "BetterCP/M")
    components = [row for row in matrix
                  if row["component"] != "BetterCP/M"
                  and row["status"].startswith("completed")
                  and row["interface_version"] != "-"
                  and row["implementation_version"] != "-"]
    lines = [
        "; Generated by tools/version_metadata.py from",
        "; metadata/subsystem-versions.tsv. Do not edit this table by hand.",
        "BCV_DESC:",
        f"        DB      'B','V',1,{len(components)}",
        "        DW      BCV_SYSTEM,BCV_RELEASE",
    ]
    for row in components:
        stem = LABELS[row["component"]]
        lines.append(f"        DW      BV_{stem}_ID,BV_{stem}_API,BV_{stem}_IMP")
    lines.extend((
        f"BCV_SYSTEM:     DB      {quoted(system['identity'])}",
        f"BCV_RELEASE:    DB      {quoted(system['implementation_version'])}",
    ))
    for row in components:
        stem = LABELS[row["component"]]
        lines.extend((
            f"BV_{stem}_ID:       DB      {quoted(row['identity'])}",
            f"BV_{stem}_API:      DB      {quoted(row['interface_version'])}",
            f"BV_{stem}_IMP:      DB      {quoted(row['implementation_version'])}",
        ))
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    INCLUDE.write_text(render(), encoding="ascii")
    print(INCLUDE.relative_to(ROOT))
