#!/usr/bin/env python3
"""Generate the resident subsystem-version descriptor from the TSV matrix."""
from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MATRIX = ROOT / "metadata/subsystem-versions.tsv"
INCLUDE = ROOT / "src/bdos/versions.inc"
CPX_INCLUDE = ROOT / "src/utilities/cpxvers.inc"
RSX_INCLUDE = ROOT / "src/utilities/rsxvers.inc"


def rows() -> list[dict[str, str]]:
    with MATRIX.open(newline="", encoding="utf-8") as source:
        return list(csv.DictReader(source, delimiter="\t"))


LABELS = {"CCP": "C", "CPX": "X", "BDOS": "D", "RSX": "R", "BIOS": "I"}
RESIDENT_IDENTITIES = {
    "BetterCP/M": "System",
    "CCP": "CCP",
    "BDOS": "BDOS",
    "BIOS": "BIOS",
}


def quoted(value: str) -> str:
    if not value.isascii() or "'" in value or "$" in value:
        raise ValueError(f"version metadata is not ZSM4-string-safe: {value!r}")
    return f"'{value}','$'"


def generated_header(title: str, final: str) -> list[str]:
    return [
        "; ********************************************************************************",
        f"; *{' ' * 20}{title:<58}*",
        "; *                                                                              *",
        "; * Generated by tools/version_metadata.py from metadata/subsystem-versions.tsv. *",
        f"; * {final:<76} *",
        "; ********************************************************************************",
        "",
    ]


def annotated(code: str, comment: str) -> str:
    return f"{code:<40}; {comment}"


def render() -> str:
    matrix = rows()
    system = next(row for row in matrix if row["component"] == "BetterCP/M")
    components = [row for row in matrix
                  if row["component"] != "BetterCP/M"
                  and row["component"] not in ("CPX", "RSX")
                  and row["status"].startswith("completed")
                  and row["interface_version"] != "-"
                  and row["implementation_version"] != "-"]
    lines = generated_header("BetterCP/M Generated Version Metadata",
                             "Do not edit this table by hand.") + [
        annotated("BCV_DESC:", "version descriptor header"),
        f"        DB      'B','V',1,{len(components)}",
        "        DW      BCV_SYSTEM,BCV_RELEASE",
    ]
    for row in components:
        stem = LABELS[row["component"]]
        lines.append(f"        DW      BV_{stem}_ID,BV_{stem}_API,BV_{stem}_IMP")
    lines.extend((
        annotated(f"BCV_SYSTEM:     DB      {quoted(RESIDENT_IDENTITIES['BetterCP/M'])}",
                  "system name"),
        annotated(f"BCV_RELEASE:    DB      {quoted(system['implementation_version'])}",
                  "system release"),
    ))
    for row in components:
        stem = LABELS[row["component"]]
        lines.extend((
            annotated(f"BV_{stem}_ID:       DB      {quoted(RESIDENT_IDENTITIES.get(row['component'], row['identity']))}",
                      f"{row['component']} subsystem identifier"),
            annotated(f"BV_{stem}_API:      DB      {quoted(row['interface_version'])}",
                      f"{row['component']} API version"),
            annotated(f"BV_{stem}_IMP:      DB      {quoted(row['implementation_version'])}",
                      f"{row['component']} implementation version"),
        ))
    return "\n".join(lines) + "\n"


def render_manager(component: str, symbol: str) -> str:
    row = next(row for row in rows() if row["component"] == component)
    value = (f"{row['identity']}: API {row['interface_version']}; "
             f"implementation {row['implementation_version']}")
    header = generated_header(f"Generated {component} Version Metadata",
                              "Do not edit by hand.")
    return "\n".join(header + [
        f"{symbol}: DB 13,10,{quoted(value)},13,10,'$' ; {component} facility version string",
    ]) + "\n"


if __name__ == "__main__":
    INCLUDE.write_text(render(), encoding="ascii")
    CPX_INCLUDE.write_text(render_manager("CPX", "CX_VERSION"), encoding="ascii")
    RSX_INCLUDE.write_text(render_manager("RSX", "RS_VERSION"), encoding="ascii")
    for path in (INCLUDE, CPX_INCLUDE, RSX_INCLUDE):
        print(path.relative_to(ROOT))
